### ISSUE TITLE
shortcut nvda+I is not reading notifications.

### ISSUE THREAD

**Issue by Danielgelsdorf** [SamKacer/IntelliJ_NVDA_Addon#12]
in IntelliJ IDEA Community Edition 2023.2.5, the current version of the addon is not reading error notifications with the nvda+I shortcut

**Comment by SamKacer** [comment]
Thank you for raising this. Another user recently raised PR #11 for resolving this. I will try to review it soon

**Comment by SamKacer** [comment]
closed by PR #11 

I also found some other bugs, so I will try to look into those as well before releasing a new version
